#!/usr/bin/env python3

import argparse
import asyncio
import sys

try:
    from os import path
    sys.path.insert(0, path.abspath(path.join(path.dirname(__file__), '..')))
    
    import main
    from docopt import docopt
except ModuleNotFoundError as error:
    print('[-] error: {}'.format(error))
    sys.exit(1)

usage = """mediacon-py '1.0001'

Usage:
    mediacon target <username> [-o FILENAME]   
    mediacon (-h | --help)
    mediacon '1.0001'

Options:
    -o, --output    save output in json format.
    -h, --help      show this screen.
    '1.0001'

def main(args):
    main.print_sexy_banner()
    username = args['<username>']
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main.verify_username(username))

    if args['--output']:
        filename = args['FILENAME']
        core.generate_json_file(filename)

if __name__ == "__main__":

    # set arguments
    args = docopt(usage, version='1.0001')
    main(args)
